backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

publish_mode: simple

collections:
  - name: "gallery"
    label: "Gallery"
    files:
      - file: "gallery.json"
        label: "Gallery Items"
        name: "gallery"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            summary: "{{fields.caption}}"
            fields:
              - { label: "Type", name: "type", widget: "select", options: ["image", "video"], default: "image" }
              - { label: "Media file", name: "src", widget: "file" }
              - { label: "Caption", name: "caption", widget: "string", required: false }
